site_name: zettelkasten-navigation
repo_url: https://github.com/terrychenzw/zettelkasten-navigation-docs
edit_uri: edit/master/docs/docs/
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
theme:
  name: material
  palette:
    primary: deep purple
  logo: assets/obsidian.png
  favicon: assets/obsidian.png
  custom_dir: overrides
nav:
  - Overview: 'index.md'
  - Metadata: 'index.md'
plugins:
  - search
